name: tasks_proj
description: Flutter app with LLM integration
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.1 

  # HTTP requests
  http: ^1.1.0
  
  # Environment variables
  flutter_dotenv: ^5.1.0
  
  # UI
  cupertino_icons: ^1.0.2

  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # For JSON serialization
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
    uses-material-design: true
    
    # Add .env file to assets
    assets:
      - .env